GROQ_API_KEY='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'
LANGCHAIN_API_KEY='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'
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_PROJECT="pr-downright-hacienda-56"
PANDASAI_API_KEY="$2a$10$x8bhQ4IEibvjy1zxxADjyehGbujFf9Yw.HTusHZoIS6bpGa4Dbfee"